apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: todo-api
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000