apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-api
  labels:
    app: todo-api
    tier: backend
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: kennedyuche/todo-app-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: postgres-db.todo-api.svc
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: secret_key
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-db.todo-api.svc:5432/postgres
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5000
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5000
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: 64m
              memory: 512Mi