apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: todo-api
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: ebs
  resources:
    requests:
      storage: 5Gi