apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: todo-api
  labels:
    tier: database
spec:
  selector:
    app: postgres-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432