apiVersion: v1
kind: Service
metadata:
  name: todo-web-service
  namespace: todo-web
  labels:
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: todo-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80