apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  namespace: todo-web
  labels:
    app: todo-web
    tier: frontend
spec:
  selector:
    matchLabels:
      app: todo-web
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: kennedyuche/todo-app-web:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # env:
          #   - name: REACT_BASE_API_URL
          #     value: http://todo-api-service.todo-api.svc:5000
          resources:
            limits:
              cpu: 64m
              memory: 512Mi