name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push-container:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the API container image
      run: docker build backend -f containers/Dockerfile.api -t ${{ secrets.DOCKER_USERNAME }}/demo-api:v1

    - name: Build the Web container image
      run: docker build frontend -f containers/Dockerfile.web -t ${{ secrets.DOCKER_USERNAME }}/demo-web:v1

    - name: Push the container images to the registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-api:v1
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-web:v1